---
apiVersion: v2
name: prometheus
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: prometheus
    version: 15.10.2
    repository: https://prometheus-community.github.io/helm-charts