---
apiVersion: v2
name: nginx-plus-ingress
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: nginx-ingress
    version: 0.15.0
    repository: https://helm.nginx.com/stable